site_name: Scientific Programming in C++ (BETA)
nav:
- Introduction: index.md
- History: history.md
- Building and running: build_and_run.md
- The C++ language: language.md
- Data structures and algorithms: data_structures_algorithms.md
- Input and output: input_output.md
- Arrays computing using Eigen: eigen.md
- Object-oriented programming: oop.md
- Organising code: code_org.md
- Debugging: debugging.md
- Mixed-language programming: mixed_language.md


theme: 
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant    
    - navigation.tracking
    - navigation.top
    - navigation.path
    - navigation.sections
    - header.autohide
    - content.code.copy
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra_css:
    - css/pdf.css
      
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      restrict_base_path: false
  - pymdownx.superfences
  - admonition
  - meta
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true  

plugins:
  - search
  - open-in-new-tab
#  - with-pdf
#  - pdf-export:
#      verbose: true
#      media_type: print
#      combined: true
